custom_menu_breadcrumbs.settings:
  type: config_object
  label: 'Custom Breadcrumbs:'
#  mapping:
#    custom_menu_breadcrumbs:
#      type: mapping
#      mapping:
#        key:
#          type: text
#          label: 'Website key value'